#!/bin/bash

hostnames=(ec2-54-85-32-37.compute-1.amazonaws.com
    ec2-54-193-70-31.us-west-1.compute.amazonaws.com
    ec2-52-38-67-246.us-west-2.compute.amazonaws.com
    ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
    ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
    ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
    ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
    ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
    ec2-54-233-185-94.sa-east-1.compute.amazonaws.com)


while getopts "p:o:u:n:i:" arg
do
    case $arg in
        p) # Port
            echo "port:$OPTARG"
            ;;
        o) # Origin server
            echo "origin:$OPTARG"
            ;;
        u) # username
            username=$OPTARG
            echo "username:$OPTARG"
            ;;
        n) # CDN-specific name
            echo "name:$OPTARG"
            ;;
        i) #private key
            #keyfile=$OPTARG
            # echo "keyfile:$OPTARG"
            ;;
        ?)
            echo "unkonw argument"
        exit 1
        ;;
        esac
done

for host in "${hostnames[@]}"
do
    echo "Deploy " $host
    ssh $username@$host 'mkdir ~/scripts/'
    scp httpserver* $username@$host:~/scripts/
    scp Makefile $username@$host:~/scripts/
    scp cache.py $username@$host:~/scripts/

done

#dnsserver=cs5700cdnproject.ccs.neu.edu
#echo "Deploy " $dnsserver
#ssh -i $keyfile $username@$dnsserver 'mkdir ~/scripts/'
#scp -i $keyfile * $username@$dnsserver:~/scripts/
#scp
